services:
  - type: web
    name: mi-app-python
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn script:app"
    pythonVersion: 3.12.1
